language: node_js
node_js:
- node
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci --build-from-source --verbose
deploy:
  skip_cleanup: true
  provider: heroku
  app: sensical
  api_key:
    secure: e5oWSs1iIoxFANYHLdh8lAQKbre3EDyPpltR1xtQ+ipv50hQ7/y3KzSrOS6MBXmmTkXlWJeqTIaztdPM7bpVUEk0iiuDQLnUbrLUSHGbMXTN+4LSozBjRYf+jJ3R9QD7vn/l/hMZi6AweCPjpV23CdW9/yYFPdvgHQjy1dfYdtNAvXKnW9RnZrdtl9TEK9WKT/GbGErm+WgewxI/kNWQ871PrM8Vl0Gorbeik77rMoGWVtOYm7vxQnNqytpCrMKzHz95YMvHhuijt1sSPpVvDazHPj0JuFgHA3UnxCJg5/DtiiUOiEcihmCFO3zAg+yAX66DXU4fEecj+a3Ia4h+co22YIUqH9546mWluJox/mtO14DmD1dDOpAQFBUdUHE+h8AK/G+Ash701NqWLTuFCBE/0iIwcYWHXDTWi7uDlW5qz6XEvHELkxlqPNy0BvGDQOUE12TdX4P9fokMwCpmWSgdna+d0rb2gt0zv4QBMqR8f0kgZvTq9P5Fmp+gPG/3Q1zF0SZfMQKYnNKkF/6gl8wzZICS/DoMkVJigz4oxWFBNX7haGGMmw+pc56YZSlWs2bNc5kkNXpqAdexp1RAB7VWav3V2W3vHfelp86Bi7A3sHKNlrp6Ij0S9lk7uTKxJnScYKcLk3KFgXdkwhCvgJmO2fHpGtuXOsgZkYMyNPk=
dd:
  secure: YKV/HXSziJvtbuveQdLE25y08EGbh2CxkX8sPOm92LJyaK5zAzCrksA0UDHAhKqTs2/OEpnXxHsHN/mmoftuOgAOHYDE2RWLTAFZ+cPXfbWCJ3MON48+gygjwHPZQY5PLUpwq9+Y6rc+TcaOq0QEnCvJ7k38yvo66HlBjpMOnrv3K+NbYnB8ODL+gMWh0iQLWDmnBhFFeChqP/7lz5zjkQY90KVsuY/m+m77BTTf9/nuYVaUybJqqG8JcF6G6xX32LGqL4fRLXVVIx1SZiR64/ciOcfV4Q37MWKEzzDwhlzLY6ZhxreoNlIB80KU4USsBoqnod0QYJPb+muuIRpZuYzgIoYt2olz9l3IJG+1X4ag74GY30DOw/xq4s3ArPjTuqAktyUwL2YNevGvew2tW918qTunSzAghOhmdzZci0r99fhIrkeDGti8E+0PCq7xrtiVtFPr5HUh2Zbb+ns91JMXZujtYofRcs3UrBV47aPekz8bzV32J9T8WyKVqbfWebHJCQzfrgIyZZWla6eSLHtm04qfznFw0CF537AzF/+bW/o6SzoYpHxZveLV82dWNQSNTC9foIJWCAsxGY4ad/FwAjXP4lgHT8C6e0fndvPm/851srN9t12BzT3fi+jFxsga8m3n3NrGdtra+25E7+bSEshOgugXSyQcZqzuaYI=
