language: node_js
node_js:
- node
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci --build-from-source --verbose
deploy:
  skip_cleanup: true
  provider: heroku
  app: sensical
  api_key:
    secure: D3xQzaPtlWsElha9TIm+Xbz+62chk6jg8fkRQ2EbNvXO+b+cEqB1iU91wL56Pi/LETnzFg9siXDU01BM6gfBtzAFYeY7yklcDSKaB7lPC347SKEaRJ/fgHMvhUinMZBFJx6g+mh6SAqQ8JVOwMbz0SJ3yDWStv1p4AtwAbaVk2szowVNDiN++R1sxoqqVutK/6O8BLqolqfr//TU+i43cYCA8pUez0yAXJnfNpZvvEKRDjM7FJ79cNE2lV9dN2QNz1Jyoxn9zZHaNCnlwkQD9ooXjFwi8yFWa//MtwKw5fjG0LGFX333cKLMMmF20BeWp37wLzkJUPQJtgg0dp8w+bOXcl2fTQK7Lwb6HUo0RbXDlmqi13pVJg8peVC8h9HXo9udOOAv3r0XcldT/XZdIL7nS7sQHYCQlaf3d2UgtbGmmpqBCO5f9BssHwVHaD3ydOv2eS85cExdEtfGGEfC/uFjyI69dchVQQ8KzdLrux8MP9RPrsTWWsIP1hVSARUWrLdB8jYSnxeQGa2uwPrICb8wBpRsJ5P53O6wPKY9OgRnDGlbMP2O7QHpqrxRe81IV1Y8Ke7F755gx4ji7LHyh3QTKBi9LOLTGEbfhFm1ZbaLntzFCtvJGlH8ZYbc414k9eUjYPlQoFu8mp8ExHdo431yqgg/OHzE1B2t+x5QU64=
dd:
  secure: YKV/HXSziJvtbuveQdLE25y08EGbh2CxkX8sPOm92LJyaK5zAzCrksA0UDHAhKqTs2/OEpnXxHsHN/mmoftuOgAOHYDE2RWLTAFZ+cPXfbWCJ3MON48+gygjwHPZQY5PLUpwq9+Y6rc+TcaOq0QEnCvJ7k38yvo66HlBjpMOnrv3K+NbYnB8ODL+gMWh0iQLWDmnBhFFeChqP/7lz5zjkQY90KVsuY/m+m77BTTf9/nuYVaUybJqqG8JcF6G6xX32LGqL4fRLXVVIx1SZiR64/ciOcfV4Q37MWKEzzDwhlzLY6ZhxreoNlIB80KU4USsBoqnod0QYJPb+muuIRpZuYzgIoYt2olz9l3IJG+1X4ag74GY30DOw/xq4s3ArPjTuqAktyUwL2YNevGvew2tW918qTunSzAghOhmdzZci0r99fhIrkeDGti8E+0PCq7xrtiVtFPr5HUh2Zbb+ns91JMXZujtYofRcs3UrBV47aPekz8bzV32J9T8WyKVqbfWebHJCQzfrgIyZZWla6eSLHtm04qfznFw0CF537AzF/+bW/o6SzoYpHxZveLV82dWNQSNTC9foIJWCAsxGY4ad/FwAjXP4lgHT8C6e0fndvPm/851srN9t12BzT3fi+jFxsga8m3n3NrGdtra+25E7+bSEshOgugXSyQcZqzuaYI=
